Deprecate DioError in favor of DioException
cfug/dio pull request #1803
Opened 2023-05-04 14:41 UTC by clragon

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

Proposed fix for #1789

2023-05-09 13:55 UTC, AlexV525 commented on dio/lib/src/dio_error.dart
> +@Deprecated('Use DioException instead')
```suggestion
@Deprecated('Use DioException instead. This will be removed in 6.0.0')
```

2023-05-09 13:55 UTC, AlexV525 commented on dio/lib/src/dio_error.dart
> +@Deprecated('Use DioExceptionType instead')
```suggestion
@Deprecated('Use DioExceptionType instead. This will be removed in 6.0.0')
```

2023-05-10 06:02 UTC, AlexV525 commented on dio/CHANGELOG.md
> +- Deprecate `DioError` in favor of `DioException`.
The entry is placed in the wrong place. It should be under the unreleased section.

2023-05-10 08:30 UTC, clragon commented
The test fail right now because I intentionally did not update the plugins with this change yet.
Should I do that anyways?

2023-05-10 09:10 UTC, kuhnroyal commented
This would go into 5.2.0? And all the plugins need to also bump constraints and a new minor version?

2023-05-10 09:17 UTC, clragon commented
Right, this change would go into 5.2.0, as its non breaking and it will tell users as soon as possible that `DioError` is deprecated.
I have updated the PR to include all plugins and their changelogs.

2023-05-10 13:50 UTC, clragon commented
I assume that would happen with the release of the versions itself, and not with this PR.
But I can certainly include that.

2023-05-11 02:03 UTC, AlexV525 commented
> But then you also need to raise the constraint in the plugins to `dio: ^5.2.0`.

That should be unnecessary IMO. No codes have been deleted actually.

2023-05-11 08:43 UTC, AlexV525 commented
> But the plugins now use the new `DioException` which is being added in `5.2.0`.

Oh indeed. They should have new constraint then.

2023-05-11 15:15 UTC, AlexV525 requested changes

2023-05-13 03:25 UTC, AlexV525 approved these changes

2023-05-15 03:09 UTC, merged