fix: in the stream mode, request cannot be canceled
cfug/dio pull request #1947
Opened 2023-08-30 11:07 UTC by lh900519

### New Pull Request Checklist

- [ ] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [ ] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [ ] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

2023-09-01 14:06 UTC, kuhnroyal commented
Thanks for your PR!

Do you have any additional information for the root problem?
The fix currently won't work when thinking about parallel requests, the closing of the HTTP client may kill other requests.
Please provide a test that reproduces the problem.

2023-09-04 08:27 UTC, lh900519 commented
```dart
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:dio/dio.dart';

void main() async {
  final dio = Dio();
  clientStream(dio, '1');
  clientStream(dio, '2');
}

Future clientStream(Dio dio, String name) async {
  try {
    final token = CancelToken();
    Timer(const Duration(seconds: 3), () {
      token.cancel("----Canceled");
    });
    const url = "https://hacker-news.firebaseio.com/v0/topstories.json";
    Response<ResponseBody> rs = await dio.get<ResponseBody>(
      url,
      options: Options(
        headers: {
          "Authorization": 'vhdrjb token"',
          "Accept": "text/event-stream",
          "Cache-Control": "no-cache",
        },
        responseType: ResponseType.stream,
      ), // set responseType to `stream`
      cancelToken: token,
    );

    rs.data?.stream
        .transform(unit8Transformer)
        .transform(const Utf8Decoder())
        .transform(const LineSplitter())
        .listen((event) {
      if (event.startsWith("event:")) {
        print("$name $event isCancelled:${token.isCancelled}");
      }
      if (event.startsWith("data:")) {
        print(
            "$name ${event.substring(0, 5)} isCancelled:${token.isCancelled}");
      }
    });
  } catch (e) {
    print('error $e');
  }
}

StreamTransformer<Uint8List, List<int>> unit8Transformer =
    StreamTransformer.fromHandlers(
  handleData: (data, sink) {
    sink.add(List<int>.from(data));
  },
);

```

Run the code with `dart test.dart`
The request was canceled using CancelToken after 3 seconds, but the terminal did not stop and continued to output.

This PR does not reuse _cachedHttpClient for stream type requests, but creates a new httpclient, and closes the newly created httpclient when using CancelToken. The processing of stream types here is the same as in 5.1.2.

2023-09-11 02:57 UTC, AlexV525 requested changes
If you have a reproducible example, please make it a test, we need tests to avoid further breakages.

2023-09-11 02:57 UTC, AlexV525 commented on dio/lib/src/adapters/io_adapter.dart
> +      {bool newClient = false}) {
These are not well-formatted (with trailing commas).

2023-09-11 02:57 UTC, AlexV525 commented on dio/lib/src/adapters/io_adapter.dart
> +      final client = _createHttpClient();
If we create new clients here, what about the closing after the client has been used?

2023-09-11 02:57 UTC, AlexV525 commented on dio/lib/src/adapters/io_adapter.dart
> +      {bool newClient = false}) {
I'd prefer `forceNotCachedClient` for better understanding, or someone else can have better namings.

2023-09-11 09:59 UTC, kuhnroyal commented
I am also wondering if there is an upstream issue for this problem. We `abort()` the request correctly, why does this not work?

2023-09-11 10:11 UTC, kuhnroyal commented
Maybe this is the source of the problem? https://github.com/dart-lang/sdk/issues/51267

2023-10-01 10:18 UTC, AlexV525 commented
Converting this to a draft until we get progress with the implementation and tests.

2023-11-14 14:15 UTC, AlexV525 commented
Should be covered by #2032.

2023-11-14 14:15 UTC, closed without merging